version: 0.1
phases:
  install:
    commands:
      - aws --version
      - pip install --upgrade awscli
      - pip install --upgrade aws-sam-cli
      - aws --version
      - sam --version
      - curl -v https://registry.npmjs.org
  build:
    commands:
      # npm install lambda functions
      - npm config set strict-ssl false
      # npm install all functions in lambda/ sub-directory
      - find ./lambda/* -maxdepth 2 -name package.json -execdir npm install --production \;
      - sam package --template-file iac.yaml --output-template-file iac.yaml --s3-bucket cf-$PREFIX-$(aws sts get-caller-identity --output text --query Account)
artifacts:
  files:
    - iac.yaml